-- 150 fake referral contest users + qualified referrals

insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-001', 'Ahmed Khan R1', 'RF0001', 4000, 4000, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-002', 'Ali Ali R2', 'RF0002', 3980, 3980, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-003', 'Hassan Malik R3', 'RF0003', 3960, 3960, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-004', 'Bilal Sheikh R4', 'RF0004', 3940, 3940, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-005', 'Usman Raza R5', 'RF0005', 3920, 3920, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-006', 'Omar Hussain R6', 'RF0006', 3900, 3900, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-007', 'Zain Ahmed R7', 'RF0007', 3880, 3880, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-008', 'Hamza Iqbal R8', 'RF0008', 3860, 3860, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-009', 'Faisal Butt R9', 'RF0009', 3840, 3840, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-010', 'Imran Mirza R10', 'RF0010', 3820, 3820, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-011', 'Ayesha Khan R11', 'RF0011', 3800, 3800, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-012', 'Fatima Ali R12', 'RF0012', 3780, 3780, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-013', 'Sana Malik R13', 'RF0013', 3760, 3760, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-014', 'Hira Sheikh R14', 'RF0014', 3740, 3740, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-015', 'Iqra Raza R15', 'RF0015', 3720, 3720, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-016', 'Zara Hussain R16', 'RF0016', 3700, 3700, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-017', 'Noor Ahmed R17', 'RF0017', 3680, 3680, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-018', 'Sara Iqbal R18', 'RF0018', 3660, 3660, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-019', 'Rabia Butt R19', 'RF0019', 3640, 3640, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-020', 'Nida Mirza R20', 'RF0020', 3620, 3620, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-021', 'Danish Khan R21', 'RF0021', 3600, 3600, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-022', 'Salman Ali R22', 'RF0022', 3580, 3580, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-023', 'Adnan Malik R23', 'RF0023', 3560, 3560, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-024', 'Farhan Sheikh R24', 'RF0024', 3540, 3540, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-025', 'Yasir Raza R25', 'RF0025', 3520, 3520, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-026', 'Kashif Hussain R26', 'RF0026', 3500, 3500, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-027', 'Rehan Ahmed R27', 'RF0027', 3480, 3480, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-028', 'Arslan Iqbal R28', 'RF0028', 3460, 3460, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-029', 'Saad Butt R29', 'RF0029', 3440, 3440, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-030', 'Anas Mirza R30', 'RF0030', 3420, 3420, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-031', 'Ahmed Khan R31', 'RF0031', 3400, 3400, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-032', 'Ali Ali R32', 'RF0032', 3380, 3380, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-033', 'Hassan Malik R33', 'RF0033', 3360, 3360, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-034', 'Bilal Sheikh R34', 'RF0034', 3340, 3340, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-035', 'Usman Raza R35', 'RF0035', 3320, 3320, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-036', 'Omar Hussain R36', 'RF0036', 3300, 3300, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-037', 'Zain Ahmed R37', 'RF0037', 3280, 3280, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-038', 'Hamza Iqbal R38', 'RF0038', 3260, 3260, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-039', 'Faisal Butt R39', 'RF0039', 3240, 3240, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-040', 'Imran Mirza R40', 'RF0040', 3220, 3220, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-041', 'Ayesha Khan R41', 'RF0041', 3200, 3200, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-042', 'Fatima Ali R42', 'RF0042', 3180, 3180, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-043', 'Sana Malik R43', 'RF0043', 3160, 3160, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-044', 'Hira Sheikh R44', 'RF0044', 3140, 3140, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-045', 'Iqra Raza R45', 'RF0045', 3120, 3120, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-046', 'Zara Hussain R46', 'RF0046', 3100, 3100, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-047', 'Noor Ahmed R47', 'RF0047', 3080, 3080, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-048', 'Sara Iqbal R48', 'RF0048', 3060, 3060, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-049', 'Rabia Butt R49', 'RF0049', 3040, 3040, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-050', 'Nida Mirza R50', 'RF0050', 3020, 3020, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-051', 'Danish Khan R51', 'RF0051', 3000, 3000, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-052', 'Salman Ali R52', 'RF0052', 2980, 2980, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-053', 'Adnan Malik R53', 'RF0053', 2960, 2960, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-054', 'Farhan Sheikh R54', 'RF0054', 2940, 2940, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-055', 'Yasir Raza R55', 'RF0055', 2920, 2920, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-056', 'Kashif Hussain R56', 'RF0056', 2900, 2900, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-057', 'Rehan Ahmed R57', 'RF0057', 2880, 2880, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-058', 'Arslan Iqbal R58', 'RF0058', 2860, 2860, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-059', 'Saad Butt R59', 'RF0059', 2840, 2840, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-060', 'Anas Mirza R60', 'RF0060', 2820, 2820, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-061', 'Ahmed Khan R61', 'RF0061', 2800, 2800, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-062', 'Ali Ali R62', 'RF0062', 2780, 2780, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-063', 'Hassan Malik R63', 'RF0063', 2760, 2760, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-064', 'Bilal Sheikh R64', 'RF0064', 2740, 2740, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-065', 'Usman Raza R65', 'RF0065', 2720, 2720, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-066', 'Omar Hussain R66', 'RF0066', 2700, 2700, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-067', 'Zain Ahmed R67', 'RF0067', 2680, 2680, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-068', 'Hamza Iqbal R68', 'RF0068', 2660, 2660, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-069', 'Faisal Butt R69', 'RF0069', 2640, 2640, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-070', 'Imran Mirza R70', 'RF0070', 2620, 2620, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-071', 'Ayesha Khan R71', 'RF0071', 2600, 2600, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-072', 'Fatima Ali R72', 'RF0072', 2580, 2580, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-073', 'Sana Malik R73', 'RF0073', 2560, 2560, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-074', 'Hira Sheikh R74', 'RF0074', 2540, 2540, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-075', 'Iqra Raza R75', 'RF0075', 2520, 2520, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-076', 'Zara Hussain R76', 'RF0076', 2500, 2500, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-077', 'Noor Ahmed R77', 'RF0077', 2480, 2480, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-078', 'Sara Iqbal R78', 'RF0078', 2460, 2460, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-079', 'Rabia Butt R79', 'RF0079', 2440, 2440, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-080', 'Nida Mirza R80', 'RF0080', 2420, 2420, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-081', 'Danish Khan R81', 'RF0081', 2400, 2400, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-082', 'Salman Ali R82', 'RF0082', 2380, 2380, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-083', 'Adnan Malik R83', 'RF0083', 2360, 2360, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-084', 'Farhan Sheikh R84', 'RF0084', 2340, 2340, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-085', 'Yasir Raza R85', 'RF0085', 2320, 2320, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-086', 'Kashif Hussain R86', 'RF0086', 2300, 2300, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-087', 'Rehan Ahmed R87', 'RF0087', 2280, 2280, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-088', 'Arslan Iqbal R88', 'RF0088', 2260, 2260, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-089', 'Saad Butt R89', 'RF0089', 2240, 2240, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-090', 'Anas Mirza R90', 'RF0090', 2220, 2220, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-091', 'Ahmed Khan R91', 'RF0091', 2200, 2200, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-092', 'Ali Ali R92', 'RF0092', 2180, 2180, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-093', 'Hassan Malik R93', 'RF0093', 2160, 2160, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-094', 'Bilal Sheikh R94', 'RF0094', 2140, 2140, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-095', 'Usman Raza R95', 'RF0095', 2120, 2120, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-096', 'Omar Hussain R96', 'RF0096', 2100, 2100, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-097', 'Zain Ahmed R97', 'RF0097', 2080, 2080, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-098', 'Hamza Iqbal R98', 'RF0098', 2060, 2060, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-099', 'Faisal Butt R99', 'RF0099', 2040, 2040, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-100', 'Imran Mirza R100', 'RF0100', 2020, 2020, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-101', 'Ayesha Khan R101', 'RF0101', 2000, 2000, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-102', 'Fatima Ali R102', 'RF0102', 1980, 1980, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-103', 'Sana Malik R103', 'RF0103', 1960, 1960, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-104', 'Hira Sheikh R104', 'RF0104', 1940, 1940, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-105', 'Iqra Raza R105', 'RF0105', 1920, 1920, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-106', 'Zara Hussain R106', 'RF0106', 1900, 1900, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-107', 'Noor Ahmed R107', 'RF0107', 1880, 1880, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-108', 'Sara Iqbal R108', 'RF0108', 1860, 1860, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-109', 'Rabia Butt R109', 'RF0109', 1840, 1840, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-110', 'Nida Mirza R110', 'RF0110', 1820, 1820, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-111', 'Danish Khan R111', 'RF0111', 1800, 1800, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-112', 'Salman Ali R112', 'RF0112', 1780, 1780, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-113', 'Adnan Malik R113', 'RF0113', 1760, 1760, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-114', 'Farhan Sheikh R114', 'RF0114', 1740, 1740, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-115', 'Yasir Raza R115', 'RF0115', 1720, 1720, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-116', 'Kashif Hussain R116', 'RF0116', 1700, 1700, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-117', 'Rehan Ahmed R117', 'RF0117', 1680, 1680, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-118', 'Arslan Iqbal R118', 'RF0118', 1660, 1660, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-119', 'Saad Butt R119', 'RF0119', 1640, 1640, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-120', 'Anas Mirza R120', 'RF0120', 1620, 1620, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-121', 'Ahmed Khan R121', 'RF0121', 1600, 1600, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-122', 'Ali Ali R122', 'RF0122', 1580, 1580, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-123', 'Hassan Malik R123', 'RF0123', 1560, 1560, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-124', 'Bilal Sheikh R124', 'RF0124', 1540, 1540, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-125', 'Usman Raza R125', 'RF0125', 1520, 1520, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-126', 'Omar Hussain R126', 'RF0126', 1500, 1500, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-127', 'Zain Ahmed R127', 'RF0127', 1480, 1480, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-128', 'Hamza Iqbal R128', 'RF0128', 1460, 1460, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-129', 'Faisal Butt R129', 'RF0129', 1440, 1440, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-130', 'Imran Mirza R130', 'RF0130', 1420, 1420, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-131', 'Ayesha Khan R131', 'RF0131', 1400, 1400, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-132', 'Fatima Ali R132', 'RF0132', 1380, 1380, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-133', 'Sana Malik R133', 'RF0133', 1360, 1360, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-134', 'Hira Sheikh R134', 'RF0134', 1340, 1340, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-135', 'Iqra Raza R135', 'RF0135', 1320, 1320, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-136', 'Zara Hussain R136', 'RF0136', 1300, 1300, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-137', 'Noor Ahmed R137', 'RF0137', 1280, 1280, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-138', 'Sara Iqbal R138', 'RF0138', 1260, 1260, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-139', 'Rabia Butt R139', 'RF0139', 1240, 1240, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-140', 'Nida Mirza R140', 'RF0140', 1220, 1220, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-141', 'Danish Khan R141', 'RF0141', 1200, 1200, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-142', 'Salman Ali R142', 'RF0142', 1180, 1180, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-143', 'Adnan Malik R143', 'RF0143', 1160, 1160, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-144', 'Farhan Sheikh R144', 'RF0144', 1140, 1140, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-145', 'Yasir Raza R145', 'RF0145', 1120, 1120, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-146', 'Kashif Hussain R146', 'RF0146', 1100, 1100, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-147', 'Rehan Ahmed R147', 'RF0147', 1080, 1080, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-148', 'Arslan Iqbal R148', 'RF0148', 1060, 1060, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-149', 'Saad Butt R149', 'RF0149', 1040, 1040, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;
insert into app_profiles (user_id, display_name, referral_code, lifetime_earned, points_balance, is_demo, status) values ('ref-demo-150', 'Anas Mirza R150', 'RF0150', 1020, 1020, true, 'active') on conflict (user_id) do update set display_name = excluded.display_name, is_demo = true;

insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-011', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-011';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-012', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-012';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-013', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-013';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-014', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-014';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-015', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-015';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-016', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-016';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-017', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-017';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-018', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-018';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-019', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-019';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-020', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-020';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-021', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-021';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-022', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-022';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-023', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-023';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-024', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-024';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-025', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-025';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-026', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-026';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-027', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-027';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-028', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-028';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-029', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-029';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-030', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-030';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-031', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-031';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-032', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-032';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-033', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-033';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-034', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-034';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-035', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-035';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-036', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-036';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-037', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-037';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-001', 'ref-demo-038', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-001' where user_id = 'ref-demo-038';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-039', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-039';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-040', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-040';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-041', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-041';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-042', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-042';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-043', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-043';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-044', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-044';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-045', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-045';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-046', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-046';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-047', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-047';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-048', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-048';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-049', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-049';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-050', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-050';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-051', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-051';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-052', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-052';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-053', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-053';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-054', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-054';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-055', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-055';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-056', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-056';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-057', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-057';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-058', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-058';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-059', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-059';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-002', 'ref-demo-060', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-002' where user_id = 'ref-demo-060';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-061', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-061';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-062', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-062';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-063', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-063';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-064', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-064';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-065', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-065';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-066', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-066';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-067', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-067';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-068', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-068';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-069', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-069';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-070', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-070';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-071', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-071';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-072', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-072';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-073', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-073';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-074', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-074';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-075', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-075';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-076', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-076';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-077', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-077';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-003', 'ref-demo-078', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-003' where user_id = 'ref-demo-078';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-079', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-079';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-080', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-080';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-081', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-081';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-082', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-082';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-083', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-083';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-084', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-084';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-085', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-085';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-086', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-086';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-087', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-087';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-088', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-088';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-089', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-089';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-090', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-090';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-091', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-091';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-004', 'ref-demo-092', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-004' where user_id = 'ref-demo-092';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-005', 'ref-demo-093', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-005' where user_id = 'ref-demo-093';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-005', 'ref-demo-094', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-005' where user_id = 'ref-demo-094';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-005', 'ref-demo-095', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-005' where user_id = 'ref-demo-095';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-005', 'ref-demo-096', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-005' where user_id = 'ref-demo-096';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-005', 'ref-demo-097', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-005' where user_id = 'ref-demo-097';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-005', 'ref-demo-098', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-005' where user_id = 'ref-demo-098';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-005', 'ref-demo-099', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-005' where user_id = 'ref-demo-099';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-005', 'ref-demo-100', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-005' where user_id = 'ref-demo-100';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-005', 'ref-demo-101', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-005' where user_id = 'ref-demo-101';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-005', 'ref-demo-102', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-005' where user_id = 'ref-demo-102';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-005', 'ref-demo-103', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-005' where user_id = 'ref-demo-103';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-005', 'ref-demo-104', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-005' where user_id = 'ref-demo-104';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-006', 'ref-demo-105', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-006' where user_id = 'ref-demo-105';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-006', 'ref-demo-106', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-006' where user_id = 'ref-demo-106';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-006', 'ref-demo-107', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-006' where user_id = 'ref-demo-107';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-006', 'ref-demo-108', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-006' where user_id = 'ref-demo-108';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-006', 'ref-demo-109', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-006' where user_id = 'ref-demo-109';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-006', 'ref-demo-110', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-006' where user_id = 'ref-demo-110';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-006', 'ref-demo-111', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-006' where user_id = 'ref-demo-111';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-006', 'ref-demo-112', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-006' where user_id = 'ref-demo-112';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-006', 'ref-demo-113', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-006' where user_id = 'ref-demo-113';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-006', 'ref-demo-114', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-006' where user_id = 'ref-demo-114';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-007', 'ref-demo-115', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-007' where user_id = 'ref-demo-115';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-007', 'ref-demo-116', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-007' where user_id = 'ref-demo-116';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-007', 'ref-demo-117', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-007' where user_id = 'ref-demo-117';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-007', 'ref-demo-118', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-007' where user_id = 'ref-demo-118';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-007', 'ref-demo-119', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-007' where user_id = 'ref-demo-119';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-007', 'ref-demo-120', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-007' where user_id = 'ref-demo-120';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-007', 'ref-demo-121', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-007' where user_id = 'ref-demo-121';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-007', 'ref-demo-122', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-007' where user_id = 'ref-demo-122';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-007', 'ref-demo-123', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-007' where user_id = 'ref-demo-123';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-008', 'ref-demo-124', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-008' where user_id = 'ref-demo-124';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-008', 'ref-demo-125', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-008' where user_id = 'ref-demo-125';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-008', 'ref-demo-126', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-008' where user_id = 'ref-demo-126';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-008', 'ref-demo-127', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-008' where user_id = 'ref-demo-127';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-008', 'ref-demo-128', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-008' where user_id = 'ref-demo-128';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-008', 'ref-demo-129', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-008' where user_id = 'ref-demo-129';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-008', 'ref-demo-130', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-008' where user_id = 'ref-demo-130';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-008', 'ref-demo-131', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-008' where user_id = 'ref-demo-131';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-009', 'ref-demo-132', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-009' where user_id = 'ref-demo-132';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-009', 'ref-demo-133', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-009' where user_id = 'ref-demo-133';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-009', 'ref-demo-134', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-009' where user_id = 'ref-demo-134';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-009', 'ref-demo-135', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-009' where user_id = 'ref-demo-135';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-009', 'ref-demo-136', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-009' where user_id = 'ref-demo-136';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-009', 'ref-demo-137', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-009' where user_id = 'ref-demo-137';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-009', 'ref-demo-138', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-009' where user_id = 'ref-demo-138';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-010', 'ref-demo-139', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-010' where user_id = 'ref-demo-139';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-010', 'ref-demo-140', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-010' where user_id = 'ref-demo-140';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-010', 'ref-demo-141', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-010' where user_id = 'ref-demo-141';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-010', 'ref-demo-142', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-010' where user_id = 'ref-demo-142';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-010', 'ref-demo-143', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-010' where user_id = 'ref-demo-143';
insert into referrals (referrer_user_id, referred_user_id, status, rewarded_at) values ('ref-demo-010', 'ref-demo-144', 'rewarded', now()) on conflict (referred_user_id) do nothing;
update app_profiles set referred_by = 'ref-demo-010' where user_id = 'ref-demo-144';

insert into settings (key, value) values
  ('contest_title', 'Referral Mega Contest'),
  ('contest_prize_1', 'iPhone 12'),
  ('contest_prize_2', 'iPad'),
  ('contest_prize_3', 'EarPods'),
  ('contest_prize_4_10', 'Gift pack')
on conflict (key) do update set value = excluded.value;